import 'package:homy/models/reels/reels_model.dart';


class DummyReels {
  static final List<ReelData> reelsData = [
    ReelData(
      id: 1,
      content: 'https://assets.mixkit.co/videos/preview/mixkit-interior-of-a-luxury-residential-house-42925-large.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
      // title: 'Modern Luxury Villa',
      description: 'Spectacular 5-bedroom villa with ocean view',
      likesCount: 1200,
      commentsCount: 150,
      // user: UserData(
      //   id: '101',
      //   name: 'Sarah Johnson',
      //   profileImage: 'https://randomuser.me/api/portraits/women/1.jpg',
      //   isVerified: true,
      //   email: 'sarah.j@example.com',
      // ),
      // propertyDetails: PropertyDetails(
      //   id: 'P101',
      //   price: 2500000,
      //   location: 'Miami Beach, FL',
      //   bedrooms: 5,
      //   bathrooms: 4,
      //   area: 4500,
      //   isFavorite: false,
      //   isSaved: false,
      // ),
    ),
    ReelData(
      id: 2,
      content: 'https://assets.mixkit.co/videos/preview/mixkit-real-estate-agent-showing-a-big-house-to-a-couple-42926-large.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6',
      description: 'Stunning industrial-style loft in the heart of the city',
      likesCount: 850,
      commentsCount: 95,
      //   user: UserData(
      //   id: '102',
      //   name: 'Mike Chen',
      //   profileImage: 'https://randomuser.me/api/portraits/men/2.jpg',
      //   isVerified: false,
      //   email: 'mike.c@example.com',
      // ),
      // propertyDetails: PropertyDetails(
      //   id: 'P102',
      //   price: 875000,
      //   location: 'Downtown Seattle, WA',
      //   bedrooms: 2,
      //   bathrooms: 2,
      //   area: 1800,
      //   isFavorite: false,
      //   isSaved: false,
      // ),
    ),
    ReelData(
      id: 3,
      content: 'https://assets.mixkit.co/videos/preview/mixkit-real-estate-agent-showing-a-house-to-a-couple-42927-large.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1576941089067-2de3c901e126',
      description: 'Beachfront property with private access',
      likesCount: 2100,
      commentsCount: 230,
      // user: UserData(
      //   id: '103',
      //   name: 'Emma Davis',
      //   profileImage: 'https://randomuser.me/api/portraits/women/3.jpg',
      //   isVerified: true,
      //   email: 'emma.d@example.com',
      // ),
      // propertyDetails: PropertyDetails(
      //   id: 'P103',
      //   price: 3200000,
      //   location: 'Malibu, CA',
      //   bedrooms: 4,
      //   bathrooms: 3,
      //   area: 3800,
      //   isFavorite: false,
      //   isSaved: false,
      // ),
    ),
    ReelData(
      id: 4,
      content: 'https://assets.mixkit.co/videos/preview/mixkit-real-estate-agent-showing-a-modern-house-to-a-couple-42928-large.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
      description: 'Luxurious cabin with panoramic mountain views',
      likesCount: 1500,
      commentsCount: 175,
      // user: UserData(
      //   id: '104',
      //   name: 'Alex Thompson',
      //   profileImage: 'https://randomuser.me/api/portraits/men/4.jpg',
      //   isVerified: true,
      //   email: 'alex.t@example.com',
      // ),
      // propertyDetails: PropertyDetails(
      //   id: 'P104',
      //   price: 1950000,
      //   location: 'Aspen, CO',
      //   bedrooms: 3,
      //   bathrooms: 2,
      //   area: 2900,
      //   isFavorite: false,
      //   isSaved: false,
      // ),
    ),
    ReelData(
      id: 5,
      content: 'https://assets.mixkit.co/videos/preview/mixkit-modern-house-interior-with-large-windows-42929-large.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90',
      description: 'Luxury penthouse with city skyline views',
      likesCount: 1800,
      commentsCount: 205,
      // user: UserData(
      //   id: '105',
      //   name: 'Lisa Wong',
      //   profileImage: 'https://randomuser.me/api/portraits/women/5.jpg',
      //   isVerified: false,
      //   email: 'lisa.w@example.com',
      // ),
      // propertyDetails: PropertyDetails(
      //   id: 'P105',
      //   price: 4100000,
      //   location: 'Manhattan, NY',
      //   bedrooms: 3,
      //   bathrooms: 3,
      //   area: 3200,
      //   isFavorite: false,
      //   isSaved: false,
      // ),
    ),
  ];
}

class DummyData {
  static final List<Map<String, dynamic>> chatList = [
    {
      'userId': 1,
      'name': 'John Doe',
      'lastMessage': 'Hey, are you available for a viewing tomorrow?',
      'time': DateTime.now().subtract(const Duration(minutes: 5)).millisecondsSinceEpoch,
      'unreadCount': 2,
      'profileImage': 'https://randomuser.me/api/portraits/men/1.jpg',
      'isOnline': true,
    },
    {
      'userId': 2,
      'name': 'Sarah Wilson',
      'lastMessage': 'The apartment looks great! What\'s the monthly rent?',
      'time': DateTime.now().subtract(const Duration(hours: 1)).millisecondsSinceEpoch,
      'unreadCount': 0,
      'profileImage': 'https://randomuser.me/api/portraits/women/2.jpg',
      'isOnline': false,
    },
    {
      'userId': 3,
      'name': 'Michael Brown',
      'lastMessage': 'Is parking included in the rent?',
      'time': DateTime.now().subtract(const Duration(hours: 2)).millisecondsSinceEpoch,
      'unreadCount': 1,
      'profileImage': 'https://randomuser.me/api/portraits/men/3.jpg',
      'isOnline': true,
    },
    {
      'userId': 4,
      'name': 'Emma Davis',
      'lastMessage': 'Thanks for showing me the property today!',
      'time': DateTime.now().subtract(const Duration(days: 1)).millisecondsSinceEpoch,
      'unreadCount': 0,
      'profileImage': 'https://randomuser.me/api/portraits/women/4.jpg',
      'isOnline': false,
    },
    {
      'userId': 5,
      'name': 'James Wilson',
      'lastMessage': 'When can I schedule a viewing?',
      'time': DateTime.now().subtract(const Duration(days: 2)).millisecondsSinceEpoch,
      'unreadCount': 3,
      'profileImage': 'https://randomuser.me/api/portraits/men/5.jpg',
      'isOnline': true,
    },
  ];
} 