version: '3.8'

services:
  sola-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SOLANA_NETWORK=devnet
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
